version: '3.8'

services:
  git-clone:
    image: alpine/git
    volumes:
      - app-data:/usr/src/app
    command: clone --single-branch --branch main https://github.com/brandgit/dashteams.git /usr/src/app
    restart: 'no'

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - git-clone
      - db
    volumes:
      - app-data:/usr/src/app
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - git-clone
    volumes:
      - app-data:/usr/src/app
    ports:
      - "8080:80"

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
      MYSQL_DATABASE: ma_base_de_donnees
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: motdepasse
    ports:
      - "8081:80"

volumes:
  db_data:
  app-data:
